### ISSUE TITLE
write-config

### ISSUE THREAD

**Issue by blondie5125** [MikkelSchubert/paleomix#16]
Hello,
I am currently working through your pipeline for future projects and am running into a problem when I try to configure the bam_pipeline. "--write-config" does not seem to work in configuring the pipeline, and I've tried many other possible variations. Every time I input "paleomix bam_pipeline --write-config", the output is just "BAM Pipeline v1.2.13.2" followed by "Usage", with the only possible commands following bam_pipeling being "help, example, makefile, dryrun, run and remap". How should I work around this? 

Thank you so much,

Sarah

**Comment by MikkelSchubert** [comment]
Sorry for the trouble, but unfortunately the documentation was slightly wrong.

You need to add the "run" or "dryrun" sub-command before you can use the --write-config option. In other words, it should look like this:
  paleomix bam_pipeline run --write-config

And thank you for letting me know about this. I've updated the documentation with the correct usage.

Cheers,
 Mikkel

**Comment by blondie5125** [comment]
Thank you Mikkel,


I got the pipeline to work for the tutorial, I appreciate the update and look forward to using it for my work.


Best,

Sarah

________________________________
