### ISSUE TITLE
Issue running the example bam_pipeline

### ISSUE THREAD

**Issue by ldutoit** [MikkelSchubert/paleomix#19]
Hi,

we are trying to run  the latest paleomix version. Everything is installed but we cannot troubleshoot the error we get back trying to run:
```
paleomix bam_pipeline run 000_makefile.yaml
```
[pipe_python_46912708195856.stderr.txt](https://github.com/MikkelSchubert/paleomix/files/2622511/pipe_python_46912708195856.stderr.txt)

[error.log](https://github.com/MikkelSchubert/paleomix/files/2622508/error.log)

Basically we get a truncated bam out of BWA ( see error log and attached .stderr file).

Could you maybe help us with that? Thank you so much for your help!

Ludovic Dutoit & Alex Verry
University of Otago, New Zealand

**Comment by MikkelSchubert** [comment]
Dear Ludovic and Alex,

Please try to upgrade your copy of PALEOMIX and let me know if that fixes
your problem.
This particular bug should have been fixed in PALEOMIX v1.2.13, while you
appear to be running v1.2.4.

Best regards,
 Mikkel

**Comment by ldutoit** [comment]
Hi Mikkel,

thank you very much for your quick reply.

Ludo
