### ISSUE TITLE
picard tools are not individual jars anymore

### ISSUE THREAD

**Issue by ginolhac** [MikkelSchubert/paleomix#2]
the documentation says that picard' version should be 1.85+.
Actually, now picard is one main command, and tools are specified as subcommands.
How to cope this that in the `jar_root` folder?

**Comment by schae234** [comment]
Hello @ginolhac, @MikkelSchubert might be able to give a better answer for supporting API changes in tools used in paleomix. In terms of this specific case, paleomix should still work with versions of picard that have the tools split out, right?

**Comment by ginolhac** [comment]
thanks for the head up @schae234. It works well with older versions of picard where tools are separared jars. I contacted @MikkelSchubert who may update *paleomix* to work only with the new picard as a new release.

**Comment by ginolhac** [comment]
done with release [v1.1.1](https://github.com/MikkelSchubert/paleomix/releases/tag/v1.1.1)
