### ISSUE TITLE
Phylo pipeline example not working

### ISSUE THREAD

**Issue by teepean** [MikkelSchubert/paleomix#20]
Hello,

I have been experimenting with PALEOMIX and have had success with BAM pipeline.

I decided to run phylogenetic pipeline but at the step 
$phylo_pipeline genotype+msa+phylogeny 000_makefile.yaml

I get an error message:

Reading makefile(s):
Error reading makefiles:
  MakefileError:
    Makefile requirement not met at 'root:chimpanzee':
      Expected value(s): key in 'Project', 'PhylogeneticInference', 'Genotyping', 'PAML', or 'MultipleSequenceAlignment'
      Observed value(s): 'chimpanzee'
      Observed type:     str

Has something changed since the example was made or what might be causing the issue?

**Comment by MikkelSchubert** [comment]
Hi,

Can you attach your '000_makefile.yaml' file?
The error you're getting suggests that you have edited/entered the
information in the wrong place, but it is impossible for me to tell what
exactly has gone wrong from the error message itself.

Best regards,
 Mikkel
