### ISSUE TITLE
GATKv4 not supported?

### ISSUE THREAD

**Issue by mscbig** [MikkelSchubert/paleomix#23]
Hello,
I've been trying to install and use paleomix and always get an error when trying to use GATK (can't locate file GenomeAnalysisTK.jar)
I've found out that in GATKv4, there is no more jar file untitled GenomeAnalysisTK.jar but two jar files launched by a gatk module. I managed to overcome this issue but it still result in an error (see above)

"Version could not be determined for GenomeAnalysisTK:

Attempted to run command:
    $ java -server -Djava.io.tmpdir=/tmp/doctorant/bam_pipeline -Djava.awt.headless=true -XX:+UseSerialGC -jar /home/doctorant/install/jar_root/GenomeAnalysisTK.jar --version

Program may be broken or a version not supported by the
pipeline; please refer to the PALEOMIX documentation.

    Required:       any version
    Search string:  ^(\d+)\.(\d+)

---------------------- Command output ----------------------
The Genome Analysis Toolkit (GATK) v4.1.4.0
HTSJDK Version: 2.20.3
Picard Version: 2.21.1" 

If I run the command, there is no error, as you can see the output is the version. So the problem remains only when using paleomix.

Plus, I've read through my search that indel realigner isn't supported anymore in GATK4. 
It seems to me that this version isn't supported by paleomix, appending the user recommandation of softwares consequently would be great. 

(Sorry if I got something wrong!)

Regards

**Comment by MikkelSchubert** [comment]
Hi,

You are correct that GATKv4 does not include the indel realigner. And that is the only GATK tool that PALEOMIX uses, so v4 is not supported, though the error message is currently not very helpful (I'll fix that). You will either need to download an older version of GATK or simply disable the indel realignment step in the pipeline.

You can disable the indel realignment step by changing

        RawBAM: no
        RealignedBAM: yes

to 

        RawBAM: yes
        RealignedBAM: no

in your project file. See here for more information:
https://paleomix.readthedocs.io/en/latest/bam_pipeline/makefile.html#options-optional-features

Best,
 Mikkel

**Comment by mscbig** [comment]
Thanks! That's what I did. But as it took me half a day to come to this point, I thought it might be helpful to put it here, for the next desperate user! 

Thanks for this great pipeline!
