### ISSUE TITLE
Change in default tmp dir?

### ISSUE THREAD

**Issue by schae234** [MikkelSchubert/paleomix#4]
Is it possible to change the default tmp dir? I think I've been able to do this in the past with the .conf file but was wondering if this was till possible and easy to answer before I go diving in and breaking things. Right now we are running out of tmp space on the cluster we are running on.

**Comment by MikkelSchubert** [comment]
Yes, you can indeed do it using a config file.
Run either pipeline with the --write-config option, to generate a config file using the current settings. You can either specify the --temp-root option along with the --write-config option, in which case that is written, or update the corresponding ini file in ~/.pypeline by hand. You can simply remove any option from the ini that you don't wish to set there.

**Comment by schae234** [comment]
That was fast! Will report back with results, but it is running now.
