### ISSUE TITLE
A problem of  PALEOMIX 2.0.0-alpha documentation

### ISSUE THREAD

**Issue by YoungLU1** [MikkelSchubert/paleomix#42]
In section 2.3 Conda installation， the URL has changed.
The right URL is ‘https://raw.githubusercontent.com/MikkelSchubert/paleomix/master/paleomix_environment.yaml > paleomix_environment.yaml‘’

thanks for your tools.

**Comment by MikkelSchubert** [comment]
Hi,

Thank you for the report!

Could you point me to exactly where you found documentation with the wrong URL?
As far as I can tell, the URL is correct in both the repository and on readthedocs for 2.0.0-alpha.

Cheers,
Mikkel

**Comment by YoungLU1** [comment]
> Hi,
> 
> Thank you for the report!
> 
> Could you point me to exactly where you found documentation with the wrong URL?
> As far as I can tell, the URL is correct in both the repository and on readthedocs for 2.0.0-alpha.
> 
>

**Comment by YoungLU1** [comment]
Hi,

https://paleomix.readthedocs.io/en/latest/
Some days ago, the latest version readthedocs on this url was not replacing the right command after you  updated the new version. But now it is right. Many thanks for your useful and good tool. 

Cheers, 
Young
