### ISSUE TITLE
Paleomix can not find picard even though it is there

### ISSUE THREAD

**Issue by themudo** [MikkelSchubert/paleomix#45]
Hi, 
I am having some problems with paleomix. I recently uninstalled paleomix and reinstalled (with conda) the latest version, created the symlink to picard at ~/install/jar_root/picard.jar and even changed the ~/.paleomix/bam_pipeline.ini option to direct paleomix directly to my picard.jar file. If I run "java -server -Djava.io.tmpdir=/tmp/gthemudo/bam_pipeline -Djava.awt.headless=true -XX:+UseSerialGC  -Xmx4g -jar /home/gthemudo/install/jar_root/picard.jar MarkDuplicates --version" on the command line I get "Version:2.27.2" as response. 
Any idea what is causing this? 
Cheers,
Gonçalo

**Comment by MikkelSchubert** [comment]
Hi Gonçalo,

Hmm, that sounds odd.

Could you try attaching the output from running paleomix?
Also, could you tell me the output from running `paleomix --version`? 
That should hopefully allow me to narrow down the problem.

Best,
Mikkel

**Comment by themudo** [comment]
Hey, sure!
Attached is the output from running paleomix.
When I run `paleomix --version` I get `paleomix v1.3.6`
[paleomix output.txt](https://github.com/MikkelSchubert/paleomix/files/8870127/paleomix.output.txt)
\1

**Comment by MikkelSchubert** [comment]
That's rather strange:
Java returns the error message `Error: Could not find or load main class`, but only when it is run through paleomix.

When you manually tried to run `java -server ...` did you also do it in the the `paleomix` conda environment?
And if not, could you try activating the `paleomix` environment and running the java command again?

Also, could you try to attach your `bam_pipeline.ini` file?

Cheers

**Comment by themudo** [comment]
Yes, I tried running `java -server ...` in the `paleomix` conda environment, outside of it java does not run.

My `bam_pipeline.ini` is as follows:

```
[Defaults]
max_threads = 32
log_level = warning
gatk_max_threads = 1
jar_root = /home/gthemudo/miniconda3/envs/paleomix/share/picard-2.27.2-0/
bwa_max_threads = 1
progress_ui = running
temp_root = /tmp/gthemudo/bam_pipeline
jre_options =
bowtie2_max_threads = 1
adapterremoval_max_threads = 1
ui_colors = on
```

**Comment by themudo** [comment]
I noticed that outside the conda environment I seem to still have paleomix v. 1.2.14 installed at ~/install/virtualenvs/paleomix/bin/paleomix although I can't remember how I installed it. Could this be conflicting with the conda instalation?

**Comment by MikkelSchubert** [comment]
I think I found the problem:

Try removing the `jre_options =` line from your `bam_pipeline.ini` file.

**Comment by themudo** [comment]
> 

Yes, that works! Thanks a lot!

**Comment by MikkelSchubert** [comment]
Great!

Empty options in the ini file are supposed to work, but I guess something broke it.
I'll see if I can release a general fix for this.

Thanks for letting me know about this problem, and just open another issue if you run into any other problems!
