### ISSUE TITLE
similar bams with rescale and non rescale

### ISSUE THREAD

**Issue by fpezzini** [MikkelSchubert/paleomix#47]
Hello, 

I am using the paleomix bam pipeline on target capture, DNA sequences from herbarium samples. I used the rescale (`mapDamage: rescale`) and no rescale (`mapDamage: no`) option but not seeing differences in general numbers of the output bam files with `samtools coverage` - would you say this could be due to not having damage in my samples? Output graphs do not show clear patterns as the ones from the documentation.

Thank you very much for any thoughts.

**Comment by MikkelSchubert** [comment]
Hi,

mapDamage performs rescaling by decreasing the base quality scores of C>T/G>A substitutions based on the estimated probability that they are the result of DNA damage. No other changes are made and the coverage should therefore be identical before and after rescaling. However, if you don't have much of a damage signal, then rescaling probably won't make much of a difference to your base qualities either.

And take care if you are running with/without rescaling using the same YAML file and in the same directory: The current version of paleomix does not always detect changes in parameters like that and BAM file(s) might not be updated if you just change the YAML file and re-run paleomix in the same directory. In this particular case, it should be enough to (re)move the final BAM files generated by the pipeline after you've tweaked the `mapDamage` feature.

Best,
Mikkel

**Comment by fpezzini** [comment]
Hi Mikkel,

Thank you very much for the quick reply. I have also check intersection and complement in SNPs for both vcf files with `bcftools stats` - virtually all SNPs are shared between rescaled and non rescale indicating that nothing was filtered out while generating and filtering the vcfs.

Also did in separate folder to be sure.

With all best wishes,

Flávia
