### ISSUE TITLE
BWA backtrack additional options added to samse, not aln

### ISSUE THREAD

**Issue by DeondeJager** [MikkelSchubert/paleomix#49]
Hi Mikkel,

I added additional options (`-n` and `-o`) for bwa backtrack in the yaml file (bam pipeline), expecting them to be applied to the `bwa aln` command (as stated in the yaml file), but instead they seem to be applied to the `bwa samse` command (see log file), which then results in an error (I assume because `bwa samse` doesn't have a `-o` option). I've attached the yaml and log files, and I'm using paleomix v1.3.7. Please can you have a look to see what's going wrong here?

Cheers,
Deon
[SCR_086_RmA009.yaml.txt](https://github.com/MikkelSchubert/paleomix/files/11478366/SCR_086_RmA009.yaml.txt)
[bam_pipeline.20230515_151100_01.log](https://github.com/MikkelSchubert/paleomix/files/11478367/bam_pipeline.20230515_151100_01.log)

**Comment by MikkelSchubert** [comment]
Hi Deon,

Thank you for the report!

You are not doing anything wrong; that is a bug in paleomix.
I'll release a fixed version Thursday or Friday.

Best,
Mikkel

**Comment by DeondeJager** [comment]
Hi Mikkel,

OK, thanks for looking into it, and for pushing a fix soon - much appreciated!

Cheers,
Deon

**Comment by MikkelSchubert** [comment]
I've released a version of paleomix that fixes this (v1.3.8).
Thanks for the report and let me know if you run into any other problems.

Cheers,
Mikkel
