### ISSUE TITLE
Errors running node

### ISSUE THREAD

**Issue by laurenhamm** [MikkelSchubert/paleomix#51]
When running the bam pipeline, I quickly hit a confusing error (see below). I have tried running this script on every available partition, with variable memory and CPU allocations, but the error remains the same. How do I fix this?

--------------------------------------
15:34:04 INFO [1/270] Started trimming PE adapters from '/global/scratch/users/l
aurenhamm/thesis/aim1/Alignment_v3/fastq_original/1_5_S12_ID_[12].fastq'
15:34:04 ERROR NodeError while trimming PE adapters from '/global/scratch/users/laurenhamm/thesis/aim1/Alignment_v3/fastq_original/1_5_S12_ID_[12].fastq':
15:34:04 INFO Saving error logs to '/global/scratch/users/laurenhamm/thesis/aim1/Alignment_v3/paleomix/bamOuts/bam_pipeline.20230717_153402_01.log'
15:34:04 ERROR     Error(s) running Node:
15:34:04 ERROR          Temporary directory: '/global/scratch/users/laurenhamm/thesis/aim1/Alignment_v3/fastq_original/5d71e6f0-32c6-41cc-b1f3-bbd9efca5eca'
15:34:04 ERROR
15:34:04 ERROR     Command = AdapterRemoval --gzip --trimns --trimqualities --threads 12 --basename \
15:34:04 ERROR                   /global/scratch/users/laurenhamm/thesis/aim1/Alignment_v3/fastq_original/5d71e6f0-32c6-41cc-b1f3-bbd9efca5eca/reads \
15:34:04 ERROR                   --collapse --file1 \
15:34:04 ERROR                   /global/scratch/users/laurenhamm/thesis/aim1/Alignment_v3/fastq_original/1_5_S12_ID_1.fastq \
15:34:04 ERROR                   --file2 \
15:34:04 ERROR                   /global/scratch/users/laurenhamm/thesis/aim1/Alignment_v3/fastq_original/1_5_S12_ID_2.fastq \
15:34:04 ERROR                   --mm 3 --minlength 25 --qualitybase 33 --qualitybase-output 33
15:34:04 ERROR     Status  = Exited with return-code 1
15:34:04 ERROR     STDOUT* = '/global/scratch/users/laurenhamm/thesis/aim1/Alignment_v3/fastq_original/5d71e6f0-32c6-41cc-b1f3-bbd9efca5eca/pipe_AdapterRemoval_47368337539856.stdout'
15:34:04 ERROR     STDERR* = '/global/scratch/users/laurenhamm/thesis/aim1/Alignment_v3/fastq_original/5d71e6f0-32c6-41cc-b1f3-bbd9efca5eca/pipe_AdapterRemoval_47368337539856.stderr'
15:34:04 ERROR     CWD     = '/global/scratch/users/laurenhamm/thesis/aim1/Alignment_v3/paleomix/bamOuts'

**Comment by MikkelSchubert** [comment]
You'll need to check the actual output from the command that failed to figure out what went wrong.

For AdapterRemoval you'll most likely you'll be able to figure out what the problem is from that based on the error messages printed to STDERR and written to the `STDERR` file. Based on the log messages you copy/pasted, the file is

    /global/scratch/users/laurenhamm/thesis/aim1/Alignment_v3/fastq_original/5d71e6f0-32c6-41cc-b1f3-bbd9efca5eca/pipe_AdapterRemoval_47368337539856.stderr

But for other programs (or if the STDERR file doesn't provide enough information) you should also check the STDOUT file, e.g:

    /global/scratch/users/laurenhamm/thesis/aim1/Alignment_v3/fastq_original/5d71e6f0-32c6-41cc-b1f3-bbd9efca5eca/pipe_AdapterRemoval_47368337539856.stdout

Best,
Mikkel

**Comment by laurenhamm** [comment]
Thanks! I was looking at the SLURM output file on accident! You can close this thread.
