### ISSUE TITLE
skip adapter-trimming

### ISSUE THREAD

**Issue by ginolhac** [MikkelSchubert/paleomix#7]
If I want to map the reads as they are in the raw FASTQ. How should I do?
In the `makefile` I think I can use the syntax (for single-end reads)

`  Single: path/raw.fastq.gz`

so `paleomix` should consider them as already trimmed. But, could trimming be an additional feature?

**Comment by MikkelSchubert** [comment]
I'm afraid that I do not understand exactly what you are asking.
You can skip the trimming step, mapping the reads as-is, if you specify
them as you've shown. This works for all read types:

LaneName:
  Single: path/raw.fastq.gz
  Paired: path/raw.{Pair}.fastq.gz
  Collapsed: path/raw.collapsed.fastq.gz

However, I am not sure what you mean by "could trimming be an additional
feature". If you want the reads to be trimmed, then you'd just write them
normally:

LaneName: path/raw.fastq.gz

Cheers

**Comment by ginolhac** [comment]
I was thinking having a `Feature` just like
```
  # To disable all features, replace with line "Features: []"
  Features:
    - Trim reads
    - Raw BAM        # Generate BAM from the raw libraries (no indel realignment)
                     #   Location: {Destination}/{Target}.{Genome}.bam
#    - Realigned BAM 
```

but forget about it. I used the old fashion way that worked out nicely.
